# Generated by Django 4.2.13 on 2024-07-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification'),
        ('tasks', '0003_plan_remove_task_category_delete_category_task_plan'),
    ]

    operations = [
    ]
